on: [pull_request]

jobs:
  light_house_job:
    runs-on: ubuntu-latest
    env:
      CI: true 
    name: Run Lighthouse to test Score 
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@master 
    - name: npm install
      id: npmi
      run: npm install
    - name: npm build
      id: npmb
      run: npm run build
    - name: lighthouse step
      id: lighthouse
      uses: diwakersurya/lh-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        command: 'npm run start'
        url: 'http://localhost:5000' 
        comment: true 
        resultUrl: 'http://localhost:5000'

  
